FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/streamlit.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY .streamlit/ ./.streamlit/

EXPOSE 7860

CMD ["streamlit", "run", "/app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]