FROM continuumio/miniconda3

RUN apt-get update && apt-get install -y unzip curl && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user
WORKDIR $HOME/app

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY --chown=user . $HOME/app

#ENTRYPOINT ["python"]