version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "7860:7860"
    volumes:
      - ./app:/app
      - ./data:/app/data

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: mlflow_service
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./ml-flow:/mlflow

  pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile.pipeline
    container_name: model_trainer
    volumes:
      - ./src:/ml-trainer/src
      - ./data:/ml-trainer/data
    environment:
      - MLFLOW_TRACKING_URI=https://qhadata-ml-flow.hf.space
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-1
    command: ["python", "src/pipeline/run.py"]
